using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PeliculasAPI.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class PeliculasController : ControllerBase
    {
        private readonly List<Pelicula> peliculas = new List<Pelicula>
        {
            new Pelicula { Id = "1", Titulo = "Jumanji: En la Selva (Todo Público)", Sinopsis = "Remake de la película homónima de 1995...", Link = "6maujJFcuxA" },
            new Pelicula { Id = "2", Titulo = "Django: Sangre de mi Sangre (+18)", Sinopsis = "Después de cumplir la condena de 15 años en prisión...", Link = "faXp0Q3glPU" },
            new Pelicula { Id = "3", Titulo = "La Noche del Demonio: La Última Llave (+14)", Sinopsis = "La parapsicóloga Dra. Elise Rainier debe enfrentar la aparición más terrible y personal hasta el momento: la que se esconde en su propia casa.", Link = "AlcCJkJCqOM" },
            new Pelicula { Id = "4", Titulo = "Paddington 2 (Todo Público)", Sinopsis = "El oso Paddington ya está felizmente integrado en casa de la familia Brown. Se ha convertido además en un miembro muy popular de la comunidad de Windsor Gardens. Su tía Lucy cumple 100 años y él tiene el regalo perfecto para ella: un maravilloso libro pop-up de la tienda de antigüedades de Mr. Gruber. Para poder comprar el libro, Paddington decidirá realizar una serie de extraños trabajos. Pero todo se complica cuando el libro es robado.", Link = "U-z9i1tfJjQ" },
            new Pelicula { Id = "5", Titulo = "Vikingos (+14)", Sinopsis = "Basada en una historia real sucedida en los tiempos precristianos de la Rus y relatada tanto en la ‘Primera Crónica Eslava’, como en ‘Las Sagas de los Reyes’ nórdica, cuando el antiguo pueblo eslavo aún mantenía fuertes lazos culturales y de sangre con los vikingos. Tras la muerte de su padre, Sviatoslav I, el joven príncipe Vladímir se ve obligado a huir de las manos de su hermanastro mayor Yaropolk, quien asesinó a su otro hermano, Oleg, para entronarse en Kiev, capital ancestral de la Rus. Exiliado en Escandinavia, el menor de los tres hermanos reúne a su alrededor fuerzas vikingas, con el fin de vengar a Oleg y ocupar el trono de su padre. Después de su travesía, el nuevo monarca se despide de las sanguinarias tradiciones paganas, llevando el cristianismo a la antigua Rus y convirtiéndose en San Vladímir el Grande.", Link = "Y9M-LfX5td8" },
            new Pelicula { Id = "6", Titulo = "La Maldición de la Casa Winchester (+14)", Sinopsis = "Basada en la historia real de Sarah Winchester (Helen Mirren), una millonaria viuda convencida de tener una maldición. Después de la repentina muerte de su marido y su hijo, cree que las almas de todas las personas que murieron por culpa del famoso rifle creado por su familia se dedican a perseguirla. Para intentar despistar a los espíritus en pena, construyó una mansión de casi 200 habitaciones con escaleras que no daban a ninguna parte y puertas que al abrirse descubrían un muro… todo con la intención de esquivar a los seres del otro mundo.", Link = "npU31mqbviA" },
            new Pelicula { Id = "7", Titulo = "Cincuenta Sombras Liberadas (+18) (HD - Doblada)", Sinopsis = "Jamie Dornan y Dakota Johnson regresan como Christian Grey y Anastasia Steele en Cincuenta Sombras Liberadas, el tercer capítulo basado en el fenómeno \\\"Cincuenta sombras\\\", best seller a nivel mundial. Ampliando los eventos que se desencadenaron en las películas taquilleras del 2015 y 2017, que recaudaron casi $ 950 millones en todo el mundo, llega la nueva entrega para el Día de los Enamorados", Link = "B1Qdbbo0Tlw" },
            new Pelicula { Id = "8", Titulo = "Locos de Amor 2 (+14)", Sinopsis = "¡Vuelve la comedia musical del año! Un hombre descorazonado que empieza a salir con una conductora que da consejos de amor en la radio. Una mujer desesperada por ser mamá y un padre soltero en sus cincuentas que solo piensa en ella. Una mujer madura que llega de Miami buscando nuevas experiencias. Una mujer divorciada que solo quiere divertirse y el hombre que no la ha olvidado desde que tenía 23 años. El resultado, una divertida comedia romántica donde los personajes descubren que nunca es tarde para volvernos Locos de Amor.", Link = "v3fspveODBI" },
            new Pelicula { Id = "9", Titulo = "El Despertar de los Muertos Vivientes (+14) (HD - Doblada)", Sinopsis = "Un pequeño grupo de servicio militar sufre una gran tragedia, todos los sobrevivientes logran convivir en un búnker subterráneo, pero no se esperan que esto tendría que ser por mucho tiempo. Todos los refugiados buscarán desesperadamente encontrar una cura, ya que todo se ha convertido en un mundo invadido por zombis, el problema será cuando ya no puedan mantenerse a salvo y el tiempo vaya contra su favor. Una película que demuestra que el miedo no se puede controlar.", Link = "xAq_0OIirnE" },
            new Pelicula { Id = "10", Titulo = "15:17 Tren a París (+14) (HD - Doblada)", Sinopsis = "El 21 de agosto de 2015, Ayoub El-Khazzani subió al tren 9364 en Bruselas rumbo a París. No había dudas de sus intenciones: tenía una AK-47, una pistola y suficientes balas para dominar a los pasajeros a bordo. Un nuevo ataque de ISIS estaba por comenzar. Lo que no esperaba encontrar Khazzani en su misión eran tres amigos estadounidenses, Anthony Sadler, Alek Skarlatos y Spencer Stone que estaban dispuestos a deternerlo. Basada en una historia real.", Link = "bHn-yCw0-VU" },
            new Pelicula { Id = "11", Titulo = "Pantera Negra", Sinopsis = "Tras los acontecimientos ocurridos en CAPITÁN AMÉRICA: CIVIL WAR, T’Challa regresa a Wakanda, su solitaria nación africana de tecnología avanzada, para asumir como rey. Sin embargo, cuando un antiguo enemigo reaparece, el temple y la fortaleza de T’Challa como rey y superhéroe son puestos a prueba al desatarse un conflicto que pone en peligro el destino de Wakanda y del mundo entero.", Link = "JcIye2DaZwI" },
            new Pelicula { Id = "12", Titulo = "La forma del Agua", Sinopsis = "Del maestro de la narrativa Guillermo del Toro, viene LA FORMA DEL AGUA —un cuento de hadas místico, que de fondo tiene la época de la Guerra Fría en los Estados Unidos, cerca de 1962. En el laboratorio secreto de alta seguridad del gobierno donde trabaja, la solitaria Elisa (Sally Hawkins) está atrapada en una vida de retraimiento. La vida de Elisa cambia para siempre cuando ella y su compañera de trabajo, Zelda (Octavia Spencer), descubren un experimento confidencial.", Link = "K8xMDEXzX-0" },
            new Pelicula { Id = "13", Titulo = "El cavernícola", Sinopsis = "En el film, Dug, humano y Hognob, jabalí, son los héroes de una aventura en la que dos civilizaciones, la de la Edad de Piedra y la de Bronce, compiten por hacerse hueco en la historia, mientras que, por casualidad, inventan el fútbol. Dug y Hognob tendrán que ayudar a su tribu, sorteando con gracia y astucia múltiples peligros, y derrotando al malvado Lord Nooth para no perder su hogar.", Link = "VDvsFizDL9Y" },
            new Pelicula { Id = "14", Titulo = "Leatherface: La Máscara del Terror", Sinopsis = "Precuela de la saga \"La Matanza de Texas\", centrada en los años de adolescencia de Leatherface, su protagonista. El joven Leatherface escapa de un hospital psiquiátrico con otros tres reclusos y secuestra a una enfermera a la que llevará a un viaje por carretera de pesadilla.", Link = "ezk5eepqL_c" },
            new Pelicula { Id = "15", Titulo = "Operación Red Sparrow", Sinopsis = "Dominika Egorova (Jennifer Lawrence) es reclutada contra su voluntad para convertirse en “gorrión”, una mujer seductora entrenada por el servicio de seguridad ruso. Dominika aprende a utilizar su cuerpo como arma, pero lucha por mantener su sentido de identidad durante el deshumanizador proceso de entrenamiento. Al encontrar su poder en un sistema injusto, Dominika emerge como una de las herramientas más eficaces del programa. Su primer objetivo es Nate Nash (Joel Edgerton), un agente de la CIA que, por su lado, está encargado de infiltrarse en los altos mandos de la inteligencia rusa. Los dos agentes jóvenes caen en un espiral de atracción y decepción, que amenaza sus carreras, lealtades y la seguridad de ambos países.", Link = "LL1_H6ePE1o" },
            new Pelicula { Id = "16", Titulo = "Una Jungla de Locura", Sinopsis = "Maurice es un pingüino… ¡Pero hay un tigre dentro de él! Y es que, este pingüino fue criado por una tigresa, así que se ha convertido en un profesional del kung-fu. Acompañado por sus amigos, un gorila, un lemur, un pez, dos sapos y una murciélaga, Maurice tratará de hacer reinar el orden y la justicia en la jungla. Claro que el diabólico koala Igor, acompañado por sus secuaces babuinos tiene la intención de destruir la jungla… Será entonces cuando la panda de la selva acudirá al rescate.", Link = "CWhbu8m5-h4" },
            new Pelicula { Id = "17", Titulo = "A tu lado", Sinopsis = "Sumida en la tristeza, Paz decide aceptar la invitación de su tío Martín y escapar de Lima para pasar unas vacaciones en un exclusivo Resort de Punta Cana. Ahí es donde conoce a Edu, el salvavidas del resort, y a todos sus amigos, con los que compartirá un frenético pero divertido viaje en la paradisíaca República Dominicana.", Link = "eAFo1okmA4s" },
            new Pelicula { Id = "18", Titulo = "Titanes del Pacífico: La Insurrección", Sinopsis = "Debido a la amenaza de invasión de terribles criaturas del océano, el programa Jeager, responsable por la creación de robots gigantes, vuelve a reactivarse. Deberán perfeccionar la construcción de robotos y evitar que estos malévolos seres acuáticos logren tomar control de la Tierra, como casi ocurrió hace años.", Link = "9GokIVXlVVw" },
            new Pelicula { Id = "19", Titulo = "Mazinger Z: Infinity", Sinopsis = "Cuando el malvado Doctor Hell ataca la Tierra, el poderoso robot gigante Mazinger Z se decide a detenerlo.", Link = "MYMXZ7Oba3Y" },
            new Pelicula { Id = "20", Titulo = "Rascacielo: Rescate en las Alturas", Sinopsis = "La estrella mundial Dwayne Johnson lidera el elenco de esta producción de Legendary Entertainment; Rascacielos, como el ex líder del equipo de rescate de rehenes del FBI y veterano de guerra, Will Ford, quien ahora evalúa la seguridad para diversos rascacielos. En una misión en China, él encuentra al edificio más alto y seguro del mundo completamente en llamas, por lo cual ha sido incriminado. Huyendo de quienes lo buscan, Will debe encontrar a los responsables, limpiar su nombre y de algún modo rescatar a su familia que se encuentra atrapada dentro del edificio…por encima de la línea de fuego.", Link = "TFWRIO0a4Qs" },
            };
            [HttpGet]
        public IActionResult ObtenerPeliculas()
        {
            return Ok(new { success = true, data = peliculas, message = "Registros encontrados" });
        }
        [HttpGet("{id}")]
        public IActionResult ObtenerPeliculaPorId(string id)
        {
            var pelicula = peliculas.FirstOrDefault(p => p.Id == id);
            if (pelicula == null)
            {
                return NotFound(new { success = false, message = "Pelicula no encontrada" });
            }
            return Ok(new { success = true, data = pelicula, message = "Pelicula encontrada" });
        }

    }
}